using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NoMansBlocks.Modules.Input.Devices {
    /// <summary>
    /// All of the possible supported keyboard keys.
    /// </summary>
    public enum KeyboardKey : byte {
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Alpha0,
        Alpha1,
        Alpha2,
        Alpha3,
        Alpha4,
        Alpha5,
        Alpha6,
        Alpha7,
        Alpha8,
        Alpha9,
        BackQuote,
        ForwardQuote,
        DoubleQuote,
        Semicolon,
        LeftBracket,
        RightBracket,
        ForwardSlash,
        BackSlash,
        LeftShift,
        RightShift,
        LeftControl,
        RightControl,
        LeftAlt,
        RightAlt,
        CapsLock,
        Tab,
        AlphaEnter,
        Backspace,
        Delete,
        Escape,
        Insert,
        Home,
        PageUp,
        PageDown,
        End,
        UpArrow,
        DownArrow,
        LeftArrow,
        RightArrow,
        Minus,
        Plus,
        Keypad0,
        Keypad1,
        Keypad2,
        Keypad3,
        Keypad4,
        Keypad5,
        Keypad6,
        Keypad7,
        Keypad8,
        Keypad9,
        KeypadEnter,
        KeypadPlus,
        KeypadMinus,
        KeypadMultiply,
        KeypadDivide,
        KeypadPeriod,
    }
}
